import LeanCode.Definitions

open MeasureTheory
open scoped BigOperators Matrix

namespace LyubarskiiNes.GeneralLattice

/-- The time coordinate of the lattice point `M (m,n)`. -/
noncomputable def latticeTime
    (M : Matrix (Fin 2) (Fin 2) ℝ) (m n : ℤ) : ℝ :=
  M 0 0 * (m : ℝ) + M 0 1 * (n : ℝ)

/-- The frequency coordinate of the lattice point `M (m,n)`. -/
noncomputable def latticeFrequency
    (M : Matrix (Fin 2) (Fin 2) ℝ) (m n : ℤ) : ℝ :=
  M 1 0 * (m : ℝ) + M 1 1 * (n : ℝ)

/-- The first-Hermite Gabor atom at the lattice point `M (m,n)`. -/
noncomputable def h1LatticeElement
    (M : Matrix (Fin 2) (Fin 2) ℝ) (m n : ℤ) : ℝ → ℂ := fun t =>
  Complex.exp
      (2 * Real.pi * Complex.I * latticeFrequency M m n * t) *
    (t - latticeTime M m n) *
    Complex.exp (-Real.pi * (t - latticeTime M m n) ^ 2)

/-- A matrix-lattice atom is the old separable atom with unit indices and its
actual time and frequency coordinates used as the two step sizes. -/
lemma h1LatticeElement_eq_h1_element
    (M : Matrix (Fin 2) (Fin 2) ℝ) (m n : ℤ) :
    h1LatticeElement M m n =
      LyubarskiiNes.h1_element (latticeTime M m n) (latticeFrequency M m n) 1 1 := by
  funext t
  simp [h1LatticeElement, LyubarskiiNes.h1_element]

/-- Every first-Hermite atom along an arbitrary matrix lattice belongs to
`L²(ℝ)`. -/
theorem memLp_h1LatticeElement
    (M : Matrix (Fin 2) (Fin 2) ℝ) (m n : ℤ) :
    MemLp (h1LatticeElement M m n) 2 (volume : Measure ℝ) := by
  rw [h1LatticeElement_eq_h1_element]
  exact LyubarskiiNes.memLp_h1
    (latticeTime M m n) (latticeFrequency M m n) 1 1

/-- A first-Hermite matrix-lattice atom as an element of `L²(ℝ)`. -/
noncomputable def h1LatticeElementLp
    (M : Matrix (Fin 2) (Fin 2) ℝ) (m n : ℤ) :
    Lp ℂ 2 (volume : Measure ℝ) :=
  (memLp_h1LatticeElement M m n).toLp

/-- The Gabor system generated by `h₁` along `M ℤ²` is a frame. -/
def IsGaborFrameForLattice
    (M : Matrix (Fin 2) (Fin 2) ℝ) : Prop :=
  ∃ A B : ℝ, 0 < A ∧ A ≤ B ∧ ∀ f : Lp ℂ 2 (volume : Measure ℝ),
    A * ‖f‖ ^ 2 ≤
        ∑' (m : ℤ) (n : ℤ),
          ‖inner ℂ f (h1LatticeElementLp M m n)‖ ^ 2
      ∧
        ∑' (m : ℤ) (n : ℤ),
          ‖inner ℂ f (h1LatticeElementLp M m n)‖ ^ 2
        ≤ B * ‖f‖ ^ 2

/-- The density of the matrix lattice `M ℤ²`. -/
noncomputable def latticeDensity
    (M : Matrix (Fin 2) (Fin 2) ℝ) : ℝ :=
  |M.det|⁻¹

/-- The diagonal matrix presenting the separable lattice `αℤ × βℤ`. -/
noncomputable def separableLatticeMatrix (α β : ℝ) :
    Matrix (Fin 2) (Fin 2) ℝ :=
  !![α, 0; 0, β]

@[simp] lemma latticeTime_separableLatticeMatrix
    (α β : ℝ) (m n : ℤ) :
    latticeTime (separableLatticeMatrix α β) m n = α * (m : ℝ) := by
  simp [latticeTime, separableLatticeMatrix]

@[simp] lemma latticeFrequency_separableLatticeMatrix
    (α β : ℝ) (m n : ℤ) :
    latticeFrequency (separableLatticeMatrix α β) m n = β * (n : ℝ) := by
  simp [latticeFrequency, separableLatticeMatrix]

@[simp] lemma det_separableLatticeMatrix (α β : ℝ) :
    (separableLatticeMatrix α β).det = α * β := by
  simp [separableLatticeMatrix, Matrix.det_fin_two]

lemma h1LatticeElement_separable
    (α β : ℝ) (m n : ℤ) :
    h1LatticeElement (separableLatticeMatrix α β) m n =
      LyubarskiiNes.h1_element α β m n := by
  funext t
  simp only [h1LatticeElement, latticeFrequency_separableLatticeMatrix,
    latticeTime_separableLatticeMatrix, LyubarskiiNes.h1_element]
  congr 2 <;> push_cast <;> ring

lemma h1LatticeElementLp_separable
    (α β : ℝ) (m n : ℤ) :
    h1LatticeElementLp (separableLatticeMatrix α β) m n =
      LyubarskiiNes.h1_element_Lp α β m n := by
  unfold h1LatticeElementLp LyubarskiiNes.h1_element_Lp
  apply MemLp.toLp_congr
  exact Filter.Eventually.of_forall fun t =>
    congrFun (h1LatticeElement_separable α β m n) t

/-- The new matrix-lattice frame predicate is a conservative extension of the
old separable predicate. -/
theorem isGaborFrameForLattice_separable_iff
    (α β : ℝ) :
    IsGaborFrameForLattice (separableLatticeMatrix α β) ↔
      LyubarskiiNes.IsGaborFrame α β := by
  simp only [IsGaborFrameForLattice, LyubarskiiNes.IsGaborFrame,
    h1LatticeElementLp_separable]

end LyubarskiiNes.GeneralLattice
