import LeanCode.GeneralLattice.GeneratorReduction

open MeasureTheory
open scoped Matrix BigOperators

namespace LyubarskiiNes.GeneralLattice

private lemma p_pos_of_coprime_gap_general {p q : ℕ}
    (hpq : Nat.Coprime p q) (hgap : q ≥ p + 2) :
    0 < p := by
  by_contra hp
  have hp0 : p = 0 := Nat.eq_zero_of_not_pos hp
  subst p
  have hq1 : q = 1 := (Nat.coprime_zero_left q).mp hpq
  omega

private lemma positive_covolume_of_density
    {δ : ℝ} {p q : ℕ}
    (hp : 0 < p) (hq : 0 < q)
    (hdensity : δ⁻¹ = (q : ℝ) / (p : ℝ)) :
    δ = (p : ℝ) / (q : ℝ) := by
  have hp0 : (p : ℝ) ≠ 0 := by exact_mod_cast (Nat.ne_of_gt hp)
  have hq0 : (q : ℝ) ≠ 0 := by exact_mod_cast (Nat.ne_of_gt hq)
  calc
    δ = (δ⁻¹)⁻¹ := by simp
    _ = (((q : ℝ) / (p : ℝ))⁻¹) := congrArg Inv.inv hdensity
    _ = (p : ℝ) / (q : ℝ) := by field_simp [hp0, hq0]

private lemma canonicalCovolumeMatrix_eq_separable (δ : ℝ) :
    canonicalCovolumeMatrix δ = separableLatticeMatrix δ 1 := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [canonicalCovolumeMatrix, separableLatticeMatrix]

/-- **Positive Lyubarskii--Nes theorem for arbitrary lattices of rational
density.**

Let `Λ = M ℤ²`.  If `M` is nonsingular, its density is the reduced rational
number `q / p`, and `q ≥ p + 2`, then the Gabor system generated by the first
Hermite function along `Λ` is a frame.  The absolute determinant makes the
statement independent of the orientation of the chosen basis.
-/
theorem lyubarskiiNes_general_positive
    (M : Matrix (Fin 2) (Fin 2) ℝ) {p q : ℕ}
    (hM : M.det ≠ 0)
    (hpq_coprime : Nat.Coprime p q)
    (hgap : q ≥ p + 2)
    (hDensity : |M.det|⁻¹ = (q : ℝ) / (p : ℝ)) :
    IsGaborFrameForLattice M := by
  have hp : 0 < p := p_pos_of_coprime_gap_general hpq_coprime hgap
  have hq : 0 < q := by omega
  let A : Matrix (Fin 2) (Fin 2) ℝ := positiveOrientation M
  have hApos : 0 < A.det := by
    dsimp [A]
    exact det_positiveOrientation_pos hM
  have hAne : A.det ≠ 0 := ne_of_gt hApos
  have hAinv : A.det⁻¹ = (q : ℝ) / (p : ℝ) := by
    rw [← abs_of_pos hApos]
    simpa [A] using hDensity
  have hAdet : A.det = (p : ℝ) / (q : ℝ) :=
    positive_covolume_of_density hp hq hAinv
  let S : Matrix (Fin 2) (Fin 2) ℝ := canonicalNormalizer A
  have hSdet : S.det = 1 := by
    dsimp [S]
    exact det_canonicalNormalizer hAne
  have hSA : S * A = canonicalCovolumeMatrix A.det := by
    dsimp [S]
    exact canonicalNormalizer_mul hAne
  rcases exists_generator_reduction hSdet Complex.I (by norm_num) A with
    ⟨τ, hτ, htransport⟩
  have hseparable :
      IsGeneralizedGaborFrameForLattice τ hτ
        (separableLatticeMatrix ((p : ℝ) / (q : ℝ)) 1) :=
    (isGeneralizedGaborFrameForLattice_separable_iff τ hτ
      ((p : ℝ) / (q : ℝ)) 1).2
      (generalized_rational_positive hτ hpq_coprime hgap)
  have hcanonical :
      IsGeneralizedGaborFrameForLattice τ hτ
        (canonicalCovolumeMatrix A.det) := by
    rw [canonicalCovolumeMatrix_eq_separable, hAdet]
    exact hseparable
  have htransformed :
      IsGeneralizedGaborFrameForLattice τ hτ (S * A) := by
    rw [hSA]
    exact hcanonical
  have hAgen :
      IsGeneralizedGaborFrameForLattice Complex.I (by norm_num) A :=
    htransport.mp htransformed
  have hAframe : IsGaborFrameForLattice A :=
    (isGeneralizedGaborFrameForLattice_I_iff A).mp hAgen
  exact (isGaborFrameForLattice_positiveOrientation_iff M).mp hAframe

end LyubarskiiNes.GeneralLattice
